
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lab-3_8
 */
public class ACP extends javax.swing.JFrame {

    /**
     * Creates new form ACP
     */
    public ACP() {
        initComponents();
        setSize(700,500);
    }
    String uname;
    public ACP(String username) {
        initComponents();
        uname = username;
        tfusername.setText(uname);
        setVisible(true);
        setSize(800, 600);
                 BufferedImage img;
        try {
            img = ImageIO.read(new File("src/pictures/adm.png"));
            BufferedImage newimg = resize(img ,back.getWidth(),back.getHeight());
            back.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        pfconfpass = new javax.swing.JPasswordField();
        pfoldpass = new javax.swing.JPasswordField();
        pfnewpass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bt = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Change Password");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -2, 800, 60);

        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });
        getContentPane().add(tfusername);
        tfusername.setBounds(370, 130, 260, 30);

        pfconfpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfconfpassActionPerformed(evt);
            }
        });
        getContentPane().add(pfconfpass);
        pfconfpass.setBounds(370, 310, 260, 30);

        pfoldpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfoldpassActionPerformed(evt);
            }
        });
        getContentPane().add(pfoldpass);
        pfoldpass.setBounds(370, 190, 260, 30);

        pfnewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfnewpassActionPerformed(evt);
            }
        });
        getContentPane().add(pfnewpass);
        pfnewpass.setBounds(370, 250, 260, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 130, 100, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Confirm Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 310, 190, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Old Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 190, 140, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("New Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 250, 150, 30);

        bt.setBackground(new java.awt.Color(255, 153, 0));
        bt.setText("Change Password");
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });
        getContentPane().add(bt);
        bt.setBounds(300, 430, 120, 40);
        getContentPane().add(back);
        back.setBounds(0, 0, 780, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfconfpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfconfpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfconfpassActionPerformed

    private void pfoldpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfoldpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfoldpassActionPerformed

    private void pfnewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfnewpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfnewpassActionPerformed

    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfusernameActionPerformed

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        String oldpass = pfoldpass.getText();
        String newpass =  pfnewpass.getText();
        String confpass =  pfconfpass.getText();
             if (oldpass.isEmpty() || newpass.isEmpty() || confpass.isEmpty())
             {
                 JOptionPane.showMessageDialog(this, "All fields are mandatory");
             }
             else if(newpass.equals(confpass))
             {
                   
               try {
                  HttpResponse<String> res = Unirest.get("http://localhost:8888/adminchangepassword")
                           .queryString("username",uname)
                           .queryString("oldpass",oldpass)
                            .queryString("newpass",newpass).asString();
                  String response = res.getBody();
                  if (response.equals("success")) 
                {
                    JOptionPane.showMessageDialog(this, "Password Changed Successfully");
                    AH obj = new AH(uname);
                } else 
                {
                    JOptionPane.showMessageDialog(this, "Invalid Old Password");
                }
               } catch (UnirestException ex) {
                   Logger.getLogger(ACP.class.getName()).log(Level.SEVERE, null, ex);
               }
  
             }
 
        
        
        
    }//GEN-LAST:event_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ACP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ACP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ACP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ACP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ACP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pfconfpass;
    private javax.swing.JPasswordField pfnewpass;
    private javax.swing.JPasswordField pfoldpass;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
