/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sharma
 */
public class Front_page extends javax.swing.JFrame {

    /**
     * Creates new form Front_page
     */
    public Front_page() {
        initComponents();
        setSize(800,600);
        setVisible(true);
       for(int i=0; i<=100; i++)
        {
           pb.setValue(100);
           pb.setString(i+"%");
           pb.setStringPainted(true);
           try
           {
            Thread.sleep(1000);
           }
           catch(Exception ex)
                   {
                      ex.printStackTrace(); 
                   }
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MADE = new javax.swing.JLabel();
        MADE1 = new javax.swing.JLabel();
        pb = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("ONLINE EXAMINATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, 1, 800, 70);

        MADE.setText("Rollno - 1705818");
        getContentPane().add(MADE);
        MADE.setBounds(0, 280, 800, 50);

        MADE1.setText("Made by - Anjali sharma");
        getContentPane().add(MADE1);
        MADE1.setBounds(0, 234, 800, 50);

        pb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pbStateChanged(evt);
            }
        });
        getContentPane().add(pb);
        pb.setBounds(-4, 494, 800, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pbStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pbStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MADE;
    private javax.swing.JLabel MADE1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar pb;
    // End of variables declaration//GEN-END:variables
}
