
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lab-3_8
 */
public class instructions extends javax.swing.JFrame {

    /**
     * Creates new form instructions
     */
    public instructions() {
        initComponents();
        setSize(800,600);
        tfinst.setEditable(false);
        setResizable(false);
         setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         BufferedImage img;
        try {
            img = ImageIO.read(new File("src/pictures/back.jpg"));
            BufferedImage newimg = resize(img ,back.getWidth(),back.getHeight());
            back.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
      BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfinst = new javax.swing.JTextArea();
        start = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Instruction");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 60);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tfinst.setColumns(20);
        tfinst.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfinst.setRows(5);
        tfinst.setText("Steps For Accessing Your Exam Online:\n\n1) Close all programs, including email\n2) Click on the https://ondemand.questionmark.eu/home/610108/ to open the exam link provided in the email from The College.\n3) Click Logon To Exam at the bottom of the screen.\nHave your Proctor enter the Username and Password provided in the email from The College and click enter.\nTo begin the exam, click on the link to the appropriate exam listed under Online Assessments.\nBefore starting the exam:\n\nPlease verify that the student’s last name appears correctly within the User ID box.\n\nDuring the exam:\n\nThe student may not use his or her textbook, course notes, or receive help from a proctor or any other outside source.\nStudents must complete the all question multiple-choice exam within the specify time frame allotted for the exam.\nStudents must not stop the session and then return to it. This is especially important in the online environment where the system will “time-out” and not allow the student or you to re-enter the exam site.\nWhat to do if your online exam is interrupted\n\nIf your online exam is interrupted, click the “Back” button on your web browser to see if you can return to the exam. If not, follow the instructions below to resume taking the exam.\nReconnect to the Internet and log back into Blackboard.\nFollow your original instructions to access the exam login page.\nAsk your proctor to re-enter the Username and Password\nHave your Proctor enter the Username and Password provided in the email from The College and click enter.\nMinimum Browser Requirements\n\nInternet Explorer 9, Firefox 1, or Google Chrome are required to log into the exam");
        jScrollPane1.setViewportView(tfinst);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 100, 630, 380);

        start.setBackground(new java.awt.Color(102, 255, 204));
        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start);
        start.setBounds(320, 510, 150, 40);
        getContentPane().add(back);
        back.setBounds(0, 0, 840, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        Start_test st = new Start_test();
        st.setVisible(true);
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new instructions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton start;
    private javax.swing.JTextArea tfinst;
    // End of variables declaration//GEN-END:variables
}
