
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lab-3_8
 */
public class user_signup extends javax.swing.JFrame {

    /**
     * Creates new form user_signup
     */
    public user_signup() {
        initComponents();
        setSize(800,600);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         setResizable(false);
        BufferedImage img;
        try {
            img = ImageIO.read(new File("src/pictures/back.jpg"));
            BufferedImage newimg = resize(img ,back.getWidth(),back.getHeight());
            back.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        signup = new javax.swing.JButton();
        confirmpass = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        lbphoto = new javax.swing.JLabel();
        browse = new javax.swing.JButton();
        tfphoto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User Signup");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Photo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 430, 140, 20);
        getContentPane().add(phone);
        phone.setBounds(290, 340, 300, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 80, 140, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("E-mail");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 270, 140, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 150, 140, 20);
        getContentPane().add(username);
        username.setBounds(290, 80, 300, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Confirm Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 210, 190, 20);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(290, 270, 300, 30);

        signup.setText("Signup");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup);
        signup.setBounds(360, 540, 100, 30);
        getContentPane().add(confirmpass);
        confirmpass.setBounds(290, 200, 300, 30);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(290, 140, 300, 30);

        lbphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbphoto);
        lbphoto.setBounds(300, 390, 160, 80);

        browse.setText("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        getContentPane().add(browse);
        browse.setBounds(630, 430, 120, 30);

        tfphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfphotoActionPerformed(evt);
            }
        });
        getContentPane().add(tfphoto);
        tfphoto.setBounds(300, 480, 160, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Phone no");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 340, 140, 20);

        msg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(msg);
        msg.setBounds(600, 144, 200, 20);
        getContentPane().add(back);
        back.setBounds(0, 0, 820, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
         try {
            
           String Username = username.getText().trim();
           String Password = password.getText();
           String Confirmpass = confirmpass.getText();
           String Email = email.getText();
           String Phone_no = phone.getText();
           String Photo = tfphoto.getText();
            /////   ##code //////
            if (Username.equals("") || Password.equals("") || Confirmpass.equals("") || Email.equals("") || Phone_no.equals("") || Photo.equals(""))
            {
                JOptionPane.showMessageDialog(this, "All fields are mandatory");
            }
               else if(Password.equals ("!=Confirmpass"))
            {
            
                JOptionPane.showMessageDialog(this, "Password doesn't match!!!!!");
            }
               else if(Password.length()>=10)
               {
                    BufferedImage img;
            try {
                img = ImageIO.read(new File("src/pictures/ok.png"));
                BufferedImage newimg = resize(img ,msg.getWidth(),msg.getHeight());
                msg.setIcon(new ImageIcon(newimg));
            } catch (IOException ex) {
                Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
               }
            else if(Phone_no.equals(">10") )
            {
                JOptionPane.showMessageDialog(this, "PHone no must contains 10 digits !!!!!");
            }
            else
            {
                try
                {
                HttpResponse<String> res = Unirest.post("http://localhost:8888/usersignup")
                        .queryString("Username",Username)
                        .queryString("Password", Password)
                        .queryString("Email",Email)
                         .queryString("Phone_no", Phone_no)
                        .field("Photo",new File(Photo)).asString();
                                                      
                String response = res.getBody();
                if (response.equals("success")) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Signup Success");
                } else 
                {
                    JOptionPane.showMessageDialog(rootPane, "Signup Failed");
                }
                }
                catch (UnirestException ex)
                {
                    ex.printStackTrace();
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_signupActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        JFileChooser jfc = new JFileChooser("C:\\");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpeg", "jpg", "bmp", "png");
        jfc.setFileFilter(filter);
        jfc.setAcceptAllFileFilterUsed(false);
        int showDialog = jfc.showDialog(this, "Open");
        if (showDialog == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            tfphoto.setText(f.getPath());
            BufferedImage bi;
            try {
                bi = ImageIO.read(f);

                BufferedImage newimage = resize(bi,200,200);
                ImageIcon ic = new ImageIcon(newimage);
                lbphoto.setIcon(ic);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_browseActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void tfphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfphotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfphotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_signup().setVisible(true);
            }
        });
    }
    BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
     }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton browse;
    private javax.swing.JPasswordField confirmpass;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbphoto;
    private javax.swing.JLabel msg;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JButton signup;
    private javax.swing.JTextField tfphoto;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
